# action.yml
name: "Create cloudformation on AWS"
description: "Deploy your cloudformation in to AWS"

inputs:
    aws-access-key:
        description: "AWS ACCESS KEY"
        required: true
        default: ""

    aws-secret-access-key:
        description: "AWS SECRET KEY"
        required: true
        default: ""

    aws-region:
        description: "Region where you want to deploy"
        required: true
        default: "ap-northeast-1"

outputs:
    result:
        description: "Show the result of deploying"

runs:
    using: "docker"
    image: "Dockerfile"
    args:
        - ${{ inputs.aws-access-key }}
        - ${{ inputs.aws-secret-access-key }}
        - ${{ inputs.aws-region }}
